# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
machine:
  java:
    version: oraclejdk8
  ruby:
    version: ruby-2.4.1
  environment:
    ANDROID_HOME: /usr/local/android-sdk-linux
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-25-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "android/build.gradle" }}-{{ checksum  "android/app/build.gradle" }}
      - run:
          name: Download Dependencies
          command: cd android/ && ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "android/build.gradle" }}-{{ checksum  "android/app/build.gradle" }}
      - run:
          name: Run Tests
          command: cd android/ && ./gradlew lint test
      - store_artifacts:
          path: android/app/build/reports
          destination: reports
      - store_test_results:
          path: android/app/build/test-results
test:
  override:
    - bundle exec danger
